### ISSUE TITLE
RG credit style

### ISSUE THREAD

**Issue by mhulse** [registerguard/raptor#1]
Awesome readme setup! :)

This is a dumb suggestion, and feel free to do what you think works, but RG style is to not have spaces between the slash for a credit line:

> Copyright &copy; 2013 [Patrick Sullivan](http://psullivan6.com) / [The Register-Guard](http://www.registerguard.com)

... if you want to comply with what we do in news, then it should be:

> Copyright &copy; 2013 [Patrick Sullivan](http://psullivan6.com)/[The Register-Guard](http://www.registerguard.com)

For example, here's a cutline/credit line by one of the photogs:

![screen shot 2013-05-18 at 12 30 33 am](https://f.cloud.github.com/assets/218624/521253/e3616778-bf8c-11e2-83b8-e8f91a51803b.png)

**Comment by psullivan6** [comment]
fixed
