### ISSUE TITLE
Padding in Chrome for maxlength

### ISSUE THREAD

**Issue by psullivan6** [registerguard/raptor#17]
I think I solved this, but check just in case. Chrome adds extra padding for a field whose width is determined by the `maxlength` attribute.

**Comment by mhulse** [comment]
Not sure if this will be of any help, as I'm not sure of your exact issue, but have you [played with `border-box`](http://www.paulirish.com/2012/box-sizing-border-box-ftw/)?

Using `border-box` on inputs can save a lot of headache as the padding becomes a part of the width.

Not sure if the Chrome padding you speak of is related to box model problems, but I thought I'd mention.
