### ISSUE TITLE
Font Hosting

### ISSUE THREAD

**Issue by psullivan6** [registerguard/raptor#21]
`raptor` uses an icon font that is currently hosted on advertising.registerguard.com, but, I assume, is running into the same cross-domain font issues as the flag, etc...

Should this custom font be hosted on fonts.rg? Can it be?

I still have a bit more digging to confirm this is the issue, but seems like it is, so I thought I'd jump on it.

@mhulse any ideas?

**Comment by mhulse** [comment]
> Should this custom font be hosted on fonts.rg? Can it be?

Definitely.

Ideally, the font's could remain with their theme's assets, but I'm not sure if it would be easy for IS dept. to setup al of our servers to allow for this. :frowning: 

Do you need connex info?

fonts.rg.com is on the new nginx server. I have to spoof the domain and connect like normal. From there, I have each of the fonts in folders named after the font and a `styles.css` at the root:

![screen shot 2013-08-05 at 11 03 59 am](https://f.cloud.github.com/assets/218624/912046/743a8194-fdf9-11e2-9348-1ecd89c73223.png)

I don't think I'm actually using `styles.css`, as I ended up incorporating all that css into Bulldog's build:

https://github.com/registerguard/bulldog/blob/master/build/files/css/less/font.less

I'm going to re-name that file with `.bak` and then we can eventually delete it.

In terms of you adding a font, the question is do we want to reorganize the folder structure? Does it make sense to keep the font folders at the root, or to put them into a theme-named folder?

For example:

/bulldog/benton/...
/bulldog/miller/...
/bulldog/rg/...
/drone/rg/...
/raptor/rg/... (but, won't raptor be using bulldog as a submodule at some point?)

... or, should we just leave them at the root and use as needed?

I could go either way. Font's are a unique thing in that they have to be hosted with a special setup ... if this wasn't the case, I'd probably just include the fonts needed for each theme within that theme's asset folder.

**Comment by psullivan6** [comment]
Could just do each font as a directory, so basically keep as is. Right now the "raptor" font is named that, so it could be next to benton, rg, etc... directories as `raptor` Will probably need the connection info after fires are put out, but if you can email or post on a private repo that'd be cool :+1:
