### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by psullivan6** [registerguard/raptor#8]
- [x] Match the style of the inputs
- [x] Make fluid sizing based on font-size
- [ ] Classes for actual `<button>`s as well as any other `html` element

**In the Wild:**
- Sign-In/Up buttons (services, Marketplace, etc...)
- Form `submit` buttons (Marketplace, Readers' Choice, email newsletters)

**Notes:**
- Use same global `.f22` as inputs for styling these?

**Comment by psullivan6** [comment]
Check the font-size.

Currently if there's a `ssh4` or something inside the `.button` then it will get reduced to 75% b/c of the `.button`s `font-size: .75em`

**Comment by mhulse** [comment]
You can also use `rem` (or even PX) values. That will use the base font size set on the `:root` element. Since we're not supporting <=IE8, then we don't need to worry about scaling in those browsers.

Decent read here: http://snook.ca/archives/html_and_css/font-size-with-rem
